### PR TITLE
CGO#15: Outdoor Points of Interest

### PR DESCRIPTION
**Pull request by neliop**
CGO #15 

- Choosing **Points of Interest** from the Quick Menu opens a page listing 6 indoor and outdoor POI categories
    - Washroom (indoor)
    - Water Fountain (indoor)
    - Elevators (indoor)
    - Restaurants (outdoor)
    - Shopping (outdoor)
    - Grocery (outdoor)

- Choosing one of the **outdoor** POI categories opens a page listing results from the Google Places API of places in that category and near the user's location

- Each place result is displayed as a Card with the place's _name_, _address_, _price level_, _rating_, and whether it is currently _open_

- Each place result also displays a _directions_ button that when pressed, opens the directions search UI with _source_ set to the user's location and _destination_ set to the selected place result

CGO #72 Bug

Issue : No shuttle services available on the weekend. Users attempting this were given an arrival time of no buses available, but the directions UI still showed up.

Fix: An alert dialog is shown to inform users that shuttle bus services are unavailable on the weekend. They are then rerouted to their destination via public transit.

### CODE REVIEW

**Review by MoreWaqar — APPROVED** [review]
Looking great, I did a bunch of testing and see no issues.

**Review by DariushN — APPROVED** [review]
Looks good to me!

**Review by danielwiktorczyk — DISMISSED** [review]
Please center this ConcordiaGo header! Here it is shifted to the left, unlike the other pages

image

**Comment by danielwiktorczyk** [comment]
LGTM! Thanks for aligning the header!

**Review by danielwiktorczyk — APPROVED** [review]

**Pull request merged**
